name: Repository dispatch for fork

on:
  create: ## Just to test rest of the steps work

jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: rrachitha/support-repo
          event-type: create_gh_action
          